# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mongoid-field_inheritance 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "mongoid-field_inheritance"
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Tobias Casper"]
  s.date = "2015-12-03"
  s.description = "Document-based inheritance for Mongoid."
  s.email = "tobias.casper@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "lib/mongoid/field_inheritance.rb",
    "lib/mongoid/field_inheritance/dependent.rb",
    "lib/mongoid/field_inheritance/dependent/base.rb",
    "lib/mongoid/field_inheritance/dependent/delete.rb",
    "lib/mongoid/field_inheritance/dependent/destroy.rb",
    "lib/mongoid/field_inheritance/fields.rb",
    "lib/mongoid/field_inheritance/inheritor.rb",
    "lib/mongoid/field_inheritance/macros.rb",
    "lib/mongoid/field_inheritance/management.rb",
    "lib/mongoid/field_inheritance/propagation.rb",
    "lib/mongoid/field_inheritance/relations.rb",
    "lib/mongoid/field_inheritance/undefined_parent_error.rb",
    "lib/mongoid/field_inheritance/uninheritable_error.rb",
    "lib/mongoid/field_inheritance/validation.rb",
    "mongoid-field_inheritance.gemspec",
    "spec/mongoid/field_inheritance/dependent_spec.rb",
    "spec/mongoid/field_inheritance/fields_spec.rb",
    "spec/mongoid/field_inheritance/macros_spec.rb",
    "spec/mongoid/field_inheritance/management_spec.rb",
    "spec/mongoid/field_inheritance/propagation_spec.rb",
    "spec/mongoid/field_inheritance/relations_spec.rb",
    "spec/mongoid/field_inheritance/validation_spec.rb",
    "spec/mongoid/field_inheritance_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/model_factory.rb"
  ]
  s.homepage = "http://github.com/tlux/mongoid-field_inheritance"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5.1"
  s.summary = "Document-based inheritance for Mongoid."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 4.0"])
      s.add_runtime_dependency(%q<mongoid>, [">= 4.0"])
      s.add_runtime_dependency(%q<mongoid-tree>, [">= 2.0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<pry-byebug>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<rubocop>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 4.0"])
      s.add_dependency(%q<mongoid>, [">= 4.0"])
      s.add_dependency(%q<mongoid-tree>, [">= 2.0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<pry-byebug>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<rubocop>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 4.0"])
    s.add_dependency(%q<mongoid>, [">= 4.0"])
    s.add_dependency(%q<mongoid-tree>, [">= 2.0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<pry-byebug>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<rubocop>, [">= 0"])
  end
end

